### ISSUE TITLE
Cloning without .git files is a 1-step process.

### ISSUE THREAD

**Issue by josephdburdick** [lassegit/npm-react-module#1]
Hi there, 
I like your idea and wanted to contribute a little by suggesting you update your README to clone this way:

`git clone --depth=1 --branch=master https://github.com/lassegit/npm-react-module CustomReactModule; rm -rf !$/.git`

**Comment by lassegit** [comment]
Thanks good idea. I can't get it to remove .git folder with the above. But this will do it:

`git clone --depth=1 --branch=master https://github.com/lassegit/npm-react-module CustomReactModule && cd $_ && sudo rm -r .git/`

**Comment by josephdburdick** [comment]
Sweet! Nice job. :+1:
